version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=warp
    ports:
      - "5432:5432"
    networks:
      - warp_network

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - elasticsearch1
    environment:
      - POSTGRES_USER=warp
      - USE_DOCKER=yes
    links:
      - postgres:postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - elasticsearch1
    networks:
      - warp_network

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.host=elasticsearch1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - warp_network
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.1.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - warp_network

volumes:
  postgres_data_dev:
  postgres_backup_dev:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  warp_network:
    driver: bridge
